export const visaStatusList = ['H1B', 'F1 OPT', 'F1 STEM OPT', 'L1', 'US Green Card', 'US Citizen', 'Canadian PR', 'Canadian Citizen']
export const employmentNatureList = ['Fulltime', 'Contract']
export const yesNoList = ['Yes', 'No']
export const roleList = ['Employee', 'Manager', 'Recruiter', 'Recruiter Manager', 'Client Manager', 'Other']
export const designationList = ['Engineer', 'Architect', 'SDE2', 'Senior Acrhitect', 'Operation Analyst', 'Technical Product Manager', 'Other']
export const employmentStatusList = ['Draft', 'Approved', 'Reject']
export const currencyTypeList = ['USD', 'INR', 'CAD']